# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-06 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='medal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold')]),
        ),
    ]
