# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20170506_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='medal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold')]),
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.FloatField(),
        ),
    ]
