# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-06 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20170506_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='medal',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Bronze'), (2, 'Silver'), (3, 'Gold')], null=True),
        ),
    ]
