# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-07 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20170506_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
